<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pages')->insert([
            [
                'image' => '20230519111640_Photo_room2.jpg',
                'title' => 'Overview',
                'content' => '<h3>Enjoy an awesome experience at our luxury resort in the Kitengela area</h3><p><br>Located just 20 minutes from the airport via the Express way, the Conrad Resort, is in the outskirts of the fast-growing Kitengela business district. Our resort is the perfect base for a relaxing experience away from the city.</p><h4>Modern accommodation in the Kitengela area</h4><p>Our 37 rooms and suites come complete with free Wi-Fi and other amenities, along with awesome views. Our breakfast is excellent; consisting of hot and cold beverages, fresh baked goods, cereals, and much more. An awesome way to kick start your day. Dine on Kenyan dishes all day in our fine restaurant. You can also enjoy food and drinks in our bars or rooftop lounge.</p><h4>Superb exercise facilities and versatile meeting spaces</h4><p>Stay in shape on your holiday at our state-of-the art gym, before relaxing in the pool area. Our scenic swimming pool lets you bask in the warm African sun or cool off with a refreshing dip. Planning a meeting or event in Kitengela? Our hotel has the best meeting facilities in town, with different versatile meeting rooms, 2 boardrooms, some working spaces, the latest in audiovisual technology, and private, secure parking for all guests.</p>'
            ],
            [
                'image' => '20230519220225_Photo_room2.jpg',
                'title' => 'Rooms',
                'content' => '<h3>However you want it, we got you!</h3><h4>Executive Room</h4><p>The Executive Room is the epitome of luxury and comfort, designed to cater to the needs of discerning travelers seeking a premium experience. These rooms are spacious, and may offer a separate living area and bedroom. The decor exudes elegance, featuring high-quality furnishings, tasteful artwork, and sophisticated color schemes. Guests staying here can enjoy a host of exclusive amenities, such as a plush king-size bed, a well-appointed work desk, a minibar stocked with premium beverages, and panoramic views. Additionally, these rooms provide access to a dedicated lounge or club, where guests can indulge in complimentary breakfast, evening cocktails, and personalized concierge services. With meticulous attention to detail and a focus on superior comfort, the Executive Room ensures an unforgettable stay for those seeking a luxurious retreat.</p><h4>Deluxe Room</h4><p>The Deluxe Room offers a perfect blend of comfort and style, catering to the needs of both business and leisure travelers. These rooms are designed with a contemporary aesthetic, featuring sleek furniture, modern decor, and soothing color palettes. With ample space and thoughtfully curated amenities, the Deluxe Room provides a comfortable environment for relaxation and productivity. Guests can expect a comfortable queen or king-size bed, a well-equipped work desk, a flat-screen TV, and a cozy seating area. The en-suite bathroom includes luxurious fixtures, a bathtub, and premium toiletries, elevating the overall experience. Whether unwinding after a day of exploration or catching up on work, the Deluxe Room offers a tranquil and inviting ambiance.</p><h4>Standard Room</h4><p>The Standard Room is a cozy and functional option, perfect for budget-conscious travelers or those looking for a comfortable base to explore the city. These rooms are designed with practicality in mind, providing essential amenities and a comfortable space to unwind. While relatively compact in size, the Standard Room doesn\'t compromise on comfort. Guests can expect a comfortable bed, a compact work desk, and a compact seating area. The decor is minimalist and modern, creating a clean and uncluttered atmosphere. The room offers en-suite bathrooms with essential facilities, ensuring a convenient stay. With its affordability and practicality, the Standard Room is an excellent choice for travelers seeking comfort and value.</p>'
            ],
            [
                'image' => '20230520115309_Photo_bar1.jpg',
                'title' => 'Restaurant and Bars',
                'content' => '<p>Hotel Restaurant:<br>Welcome to our exquisite hotel restaurant, where culinary artistry meets unmatched elegance. Step into a world of gastronomic delights, where the vibrant ambiance harmonizes with the tantalizing aromas wafting from our open kitchen. Our talented chefs skillfully craft a diverse menu featuring both local and international flavors, using only the finest seasonal ingredients. Whether you\'re savoring a perfectly seared steak, indulging in a delectable seafood creation, or delighting in a decadent dessert, every dish is a symphony of taste that will leave you craving more. Impeccable service and an extensive wine list complete the unforgettable dining experience.</p><p>Bars:<br>Introducing our two captivating bars, where libation and ambiance unite to create an atmosphere of pure relaxation and enjoyment. The first bar, nestled in a cozy corner of our hotel, exudes an intimate charm, perfect for indulging in handcrafted cocktails infused with innovative flavors. Our mixologists are masters of their craft, concocting delightful creations that will tantalize your taste buds. For a livelier scene, head to our second bar, where the energy is infectious, and the music keeps you grooving into the night. With an extensive selection of premium spirits, a vibrant dance floor, and a team of charismatic bartenders, this bar promises an unforgettable evening of celebration and revelry.</p><p>Rooftop Lounge:<br>Elevate your senses and bask in breathtaking views at our exclusive rooftop lounge. Perched high above the cityscape, this hidden oasis offers a haven of serenity and sophistication. Step onto the open-air terrace, where plush seating invites you to unwind while you soak in the panoramic vistas stretching as far as the eye can see. Sip on handcrafted cocktails expertly prepared by our mixologists as you savor delectable bites from our rooftop menu. Whether you\'re watching the sunset paint the sky in hues of gold and crimson or gazing at the city\'s sparkling lights, the rooftop lounge provides an unrivaled setting for an unforgettable evening, creating memories that will linger long after you\'ve departed.</p>'
            ],
            [
                'image' => '20230520122634_Photo_boardroom1.jpg',
                'title' => 'Conference Facilities',
                'content' => '<p>Large Conference Halls:<br>Welcome to our prestigious hotel, where world-class events come to life in our two expansive conference halls. These grand venues are designed to accommodate gatherings of any scale, from corporate conventions to elegant galas. With state-of-the-art audiovisual technology and flexible seating arrangements, our conference halls provide a seamless blend of functionality and sophistication. Impeccable service and attention to detail ensure that every aspect of your event is flawlessly executed. From the moment you step through our doors, you\'ll be immersed in an atmosphere of professionalism and refinement, where ideas flourish and connections thrive.</p><p>Medium-Sized Boardrooms:<br>For more intimate gatherings and executive meetings, we offer two stylish boardrooms that exude an air of exclusivity and refinement. These well-appointed spaces are designed with your utmost comfort and productivity in mind. Equipped with cutting-edge audiovisual equipment and comfortable seating, our boardrooms provide the perfect setting for strategic discussions and decision-making. Our dedicated staff is on hand to assist with any technical requirements or catering needs, ensuring a seamless experience from start to finish. Elevate your meetings to new heights of excellence in our sophisticated boardrooms, where ideas are born and collaborations flourish.</p><p>Small Working Spaces for Hire:<br>At our hotel, we understand the importance of flexibility and convenience, which is why we offer two cozy and functional working spaces for hire. These intimate settings are ideal for individuals or small teams looking for a quiet and productive environment. Equipped with high-speed internet access and ergonomic workstations, our small working spaces provide all the essentials to get the job done. Whether you need a private room for brainstorming sessions, client meetings, or focused work, our spaces offer the tranquility and amenities you require. Enjoy the privacy and comfort of these dedicated areas, where productivity thrives and creativity blossoms.</p>'
            ],
            [
                'image' => '20230520123457_Photo_swimming3.jpg',
                'title' => 'Fun and Fitness',
                'content' => '<p>Indulge in leisure and wellness at our hotel\'s vibrant swimming pool and state-of-the-art gym. Dive into a world of fun and relaxation as you immerse yourself in our sparkling swimming pool. With its inviting waters, water slides, and rejuvenating whirlpool, our pool is the perfect place to unwind, splash around, or simply soak up the sun on our comfortable loungers. Meanwhile, fitness enthusiasts will find their haven in our fully equipped gym. Whether you prefer cardio workouts, strength training, or group exercise classes, our gym offers a comprehensive range of equipment and facilities to cater to all fitness levels. Stay active and refreshed during your stay as you make the most of our hotel\'s dynamic swimming pool and invigorating gym.</p>'
            ],
            [
                'image' => '20230520124211_Photo_grounds1.jpg',
                'title' => 'Open Air Events',
                'content' => '<p>Discover a captivating oasis nestled within our hotel\'s grounds, providing an idyllic setting for weddings and outdoor events. Immerse yourself in the natural beauty that surrounds you as you explore our meticulously landscaped gardens, adorned with vibrant blooms and lush greenery. Our expansive outdoor venue offers a picturesque backdrop, perfect for exchanging vows or hosting a memorable celebration. With ample space to accommodate both intimate ceremonies and grand receptions, our grounds provide the flexibility to bring your vision to life. From elegant gazebos to serene ponds, every corner of our enchanting outdoor space has been designed to create an ambiance of romance and celebration, making your special day truly unforgettable.</p><p>Families with young ones will delight in our hotel\'s dedicated play area, designed to keep children entertained and engaged. Watch as their faces light up with joy as they explore a world of imagination and adventure. Our play area features a range of age-appropriate equipment, including swings, slides, and climbing structures, ensuring that children of all ages can have a fantastic time. Safety is our utmost priority, and our play area is built with secure and child-friendly materials, providing parents with peace of mind. Whether they\'re making new friends, building sandcastles in the sandpit, or enjoying playful moments under the sun, our kids\' play area is a haven of fun and laughter, creating cherished memories for the whole family to treasure.</p>'
            ],
            [
                'image' => '20230520124526_Photo_contacts1.jpg',
                'title' => 'Contact Us',
                'content' => '<p>We value your comfort and satisfaction above all else. Should you require any assistance or have any inquiries during your stay, please do not hesitate to contact our dedicated staff. We are here to ensure your experience with us is nothing short of exceptional. Your needs are our top priority, and we are always just a phone call away, ready to assist you in any way we can.</p>'
            ],
        ]);
    }
}
